apiVersion: v1
name: scaleway-csi
version: 0.0.1
appVersion: 0.1.5
kubeVersion: ">=1.17.0-0"
description: A Helm chart to install the Scaleway Block Volume CSI Driver inside a Kubernetes cluster.
sources:
  - https://github.com/fraserdarwent/scaleway-csi
home: https://github.com/fraserdarwent/scaleway-csi
maintainers:
  - name: Fraser Darwent
    email: fraser@darwen.tf
