kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaleway-csi-node-driver-registrar
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
