kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaleway-csi-node-driver-registrar
subjects:
  - kind: ServiceAccount
    name: scaleway-csi-node
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: scaleway-csi-node-driver-registrar
  apiGroup: rbac.authorization.k8s.io
