kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaleway-csi-snapshotter
subjects:
  - kind: ServiceAccount
    name: scaleway-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: scaleway-csi-snapshotter
  apiGroup: rbac.authorization.k8s.io
