kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaleway-csi-attacher
subjects:
  - kind: ServiceAccount
    name: scaleway-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: scaleway-csi-attacher
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaleway-csi-controller
subjects:
  - kind: ServiceAccount
    name: scaleway-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: scaleway-csi-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role
subjects:
  - kind: ServiceAccount
    name: scaleway-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-resizer
  apiGroup: rbac.authorization.k8s.io
