apiVersion: v1
entries:
  scaleway-csi:
  - apiVersion: v1
    appVersion: 0.1.5
    created: "2020-11-23T19:12:50.337145Z"
    description: A Helm chart to install the Scaleway Block Volume CSI Driver inside
      a Kubernetes cluster.
    digest: dcb712ffa84a5de9e7dd6728b47ab241d3058fd71709477db3474111406cb13e
    home: https://github.com/fraserdarwent/scaleway-csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: fraser@darwen.tf
      name: Fraser Darwent
    name: scaleway-csi
    sources:
    - https://github.com/fraserdarwent/scaleway-csi
    urls:
    - https://raw.githubusercontent.com/fraserdarwent/scaleway-csi/add-helm-chart/charts/scaleway-csi-0.0.1.tgz
    version: 0.0.1
generated: "2020-11-23T19:12:50.336514Z"
